// 量子力学 I & II（東大理物 院試対策）
export default {
  id: "qm",
  category: "物理",
  title: "量子力学",
  author: "",
  edition: "I & II",
  subtitle: "東大理物 院試",
  totalPages: 610,
  weekCount: 16,
  defaultStartDate: "2026-02-24",

  chapters: [
    // === Volume I ===
    {
      id: 1,
      title: "量子論の誕生",
      startPage: 1,
      endPage: 14,
      week: 1,
      importance: 2,
      gap: "小",
      sections: [
        { id: "1-1", title: "黒体輻射とエネルギー量子の発見：Planck", startPage: 2, endPage: 3 },
        { id: "1-2", title: "光電効果：Einstein", startPage: 4, endPage: 4 },
        { id: "1-3", title: "Compton効果：Compton", startPage: 5, endPage: 6 },
        { id: "1-4", title: "粒子性と波動性", startPage: 7, endPage: 7 },
        { id: "1-5", title: "de Broglie仮説とDavisson-Germerの実験", startPage: 8, endPage: 10 },
        { id: "1-6", title: "原子スペクトルの量子化：Bohr", startPage: 11, endPage: 14 },
      ],
      examTopics: ["直接は出ないが前期量子論の理解は前提"],
      notes: "14ページ。歴史的導入。速読でOK。",
    },
    {
      id: 2,
      title: "Schrödingerの波動方程式",
      startPage: 15,
      endPage: 47,
      week: 1,
      importance: 3,
      gap: "小〜中",
      sections: [
        { id: "2-1", title: "重ね合わせの原理と波束", startPage: 16, endPage: 25 },
        { id: "2-2", title: "Schrödingerの波動方程式", startPage: 26, endPage: 26 },
        { id: "2-3", title: "波動関数とBornの確率解釈", startPage: 27, endPage: 28 },
        { id: "2-4", title: "確率の保存と確率の流れ", startPage: 29, endPage: 30 },
        { id: "2-5", title: "物理量の期待値と演算子", startPage: 31, endPage: 37 },
        { id: "2-6", title: "定常状態", startPage: 38, endPage: 39 },
        { id: "2-7", title: "Ehrenfestの定理と古典的極限", startPage: 40, endPage: 47 },
      ],
      examTopics: [
        "確率の流れの計算",
        "期待値と演算子の関係",
        "Ehrenfestの定理",
      ],
      notes: "33ページ。量子力学の基礎。§5の演算子は全体の土台。",
    },
    {
      id: 3,
      title: "1次元の量子系",
      startPage: 48,
      endPage: 90,
      week: 2,
      importance: 5,
      gap: "中",
      sections: [
        { id: "3-1", title: "1次元Schrödinger方程式の一般的性質", startPage: 49, endPage: 51 },
        { id: "3-2", title: "波動の反射と透過", startPage: 52, endPage: 54 },
        { id: "3-3", title: "ポテンシャル障壁とトンネル効果I：長方形障壁", startPage: 55, endPage: 61 },
        { id: "3-4", title: "ポテンシャル障壁とトンネル効果II：一般の場合", startPage: 62, endPage: 65 },
        { id: "3-5", title: "束縛状態：井戸型ポテンシャル", startPage: 66, endPage: 68 },
        { id: "3-6", title: "周期的ポテンシャル：Kronig-Penney模型", startPage: 69, endPage: 72 },
        { id: "3-7", title: "1次元調和振動子", startPage: 73, endPage: 74 },
        { id: "3-8", title: "階段型ポテンシャルでの波束のふるまい", startPage: 75, endPage: 90 },
      ],
      examTopics: [
        "トンネル効果（透過係数の計算）",
        "井戸型ポテンシャルの束縛状態",
        "1次元調和振動子",
        "反射・透過係数",
      ],
      notes: "★43ページ★ 院試最頻出の一つ。全ての問題を手で解くこと。",
    },
    {
      id: 4,
      title: "量子力学の基本的な性質",
      startPage: 91,
      endPage: 122,
      week: 3,
      importance: 4,
      gap: "中",
      sections: [
        { id: "4-1", title: "物理量とエルミート演算子", startPage: 92, endPage: 93 },
        { id: "4-2", title: "エルミート演算子の固有関数と固有値", startPage: 94, endPage: 95 },
        { id: "4-3", title: "エルミート演算子の固有関数の性質I：離散スペクトル", startPage: 96, endPage: 99 },
        { id: "4-4", title: "エルミート演算子の固有関数の性質II：連続スペクトル", startPage: 100, endPage: 104 },
        { id: "4-5", title: "波動関数の空間", startPage: 105, endPage: 106 },
        { id: "4-6", title: "1つの状態で複数の物理量が決まった値をとる条件", startPage: 107, endPage: 108 },
        { id: "4-7", title: "量子力学における演算子法", startPage: 109, endPage: 122 },
      ],
      examTopics: [
        "エルミート演算子の性質の証明",
        "不確定性関係の導出",
        "同時固有状態と交換関係",
        "完全性関係",
      ],
      notes: "32ページ。形式的だが§6, §7は出題の土台。",
    },
    {
      id: 5,
      title: "中心力場のSchrödinger方程式",
      startPage: 123,
      endPage: 169,
      week: 4,
      importance: 5,
      gap: "中〜大",
      sections: [
        { id: "5-1", title: "Schrödinger方程式をつくる一般的規則", startPage: 124, endPage: 127 },
        { id: "5-2", title: "極座標による3次元のSchrödinger方程式", startPage: 128, endPage: 131 },
        { id: "5-3", title: "角変数の分離：球面調和関数", startPage: 132, endPage: 135 },
        { id: "5-4", title: "動径方程式", startPage: 136, endPage: 139 },
        { id: "5-5", title: "球面波", startPage: 140, endPage: 140 },
        { id: "5-6", title: "球対称な井戸型ポテンシャル：束縛状態", startPage: 141, endPage: 144 },
        { id: "5-7", title: "2体問題：重心運動の分離", startPage: 145, endPage: 147 },
        { id: "5-8", title: "水素原子", startPage: 148, endPage: 169 },
      ],
      examTopics: [
        "球面調和関数の性質",
        "水素原子のエネルギー準位と波動関数",
        "動径方程式の解法",
        "2体問題の換算質量",
      ],
      notes: "★47ページ★ 院試超頻出。§8水素原子は必ず解けるように。",
    },
    {
      id: 6,
      title: "量子力学の体系",
      startPage: 170,
      endPage: 215,
      week: 5,
      importance: 4,
      gap: "大",
      sections: [
        { id: "6-1", title: "量子力学の枠組み", startPage: 171, endPage: 173 },
        { id: "6-2", title: "量子力学における確率と物理量の測定", startPage: 174, endPage: 176 },
        { id: "6-3", title: "ブラ・ケット記号", startPage: 177, endPage: 185 },
        { id: "6-4", title: "Schrödinger描像とHeisenberg描像", startPage: 186, endPage: 187 },
        { id: "6-5", title: "正準交換関係と正準量子化", startPage: 188, endPage: 197 },
        { id: "6-6", title: "交換子とPoisson括弧", startPage: 198, endPage: 200 },
        { id: "6-7", title: "調和振動子と生成・消滅演算子", startPage: 201, endPage: 215 },
      ],
      examTopics: [
        "ブラ・ケット記法での計算",
        "Heisenberg描像での運動方程式",
        "生成・消滅演算子による調和振動子",
        "コヒーレント状態",
      ],
      notes: "★46ページ★ §3ブラケットと§7生成消滅演算子は最重要。",
    },
    {
      id: 7,
      title: "角運動量と対称性",
      startPage: 216,
      endPage: 277,
      week: 6,
      importance: 5,
      gap: "大",
      sections: [
        { id: "7-1", title: "対称性と保存量", startPage: 217, endPage: 225 },
        { id: "7-2", title: "群", startPage: 226, endPage: 238 },
        { id: "7-3", title: "運動量と角運動量", startPage: 239, endPage: 243 },
        { id: "7-4", title: "角運動量の固有状態", startPage: 244, endPage: 250 },
        { id: "7-5", title: "軌道角運動量とスピン角運動量", startPage: 251, endPage: 257 },
        { id: "7-6", title: "角運動量の合成", startPage: 258, endPage: 262 },
        { id: "7-7", title: "その他の対称性", startPage: 263, endPage: 277 },
      ],
      examTopics: [
        "角運動量の交換関係と昇降演算子",
        "角運動量の合成（Clebsch-Gordan係数）",
        "スピンの行列表現",
        "パリティ",
      ],
      notes: "★62ページの最大章★ 院試最頻出。§4-6は特に重要。",
    },
    // === Volume II ===
    {
      id: 8,
      title: "磁場中の荷電粒子",
      startPage: 291,
      endPage: 319,
      week: 8,
      importance: 4,
      gap: "中",
      sections: [
        { id: "8-1", title: "外場中の古典粒子", startPage: 292, endPage: 295 },
        { id: "8-2", title: "外場中の粒子の量子力学", startPage: 296, endPage: 300 },
        { id: "8-3", title: "一様な磁場中の荷電粒子", startPage: 301, endPage: 304 },
        { id: "8-4", title: "Aharonov-Bohm効果", startPage: 305, endPage: 311 },
        { id: "8-5", title: "スピンをもつ粒子の固有磁気モーメント", startPage: 312, endPage: 319 },
      ],
      examTopics: [
        "Landau準位",
        "Aharonov-Bohm効果",
        "ゲージ不変性",
      ],
      notes: "29ページ。Landau準位とAB効果は頻出。",
    },
    {
      id: 9,
      title: "摂動論",
      startPage: 320,
      endPage: 366,
      week: 9,
      importance: 5,
      gap: "大",
      sections: [
        { id: "9-1", title: "時間によらない摂動論I：縮退のない場合", startPage: 321, endPage: 327 },
        { id: "9-2", title: "時間によらない摂動論II：縮退のある場合", startPage: 328, endPage: 332 },
        { id: "9-3", title: "相互作用表示", startPage: 333, endPage: 337 },
        { id: "9-4", title: "時間による摂動論", startPage: 338, endPage: 345 },
        { id: "9-5", title: "連続スペクトルへの遷移", startPage: 346, endPage: 355 },
        { id: "9-6", title: "断熱因子", startPage: 356, endPage: 366 },
      ],
      examTopics: [
        "非縮退摂動論（エネルギー補正の計算）",
        "縮退摂動論（Stark効果等）",
        "Fermiの黄金律",
        "時間依存摂動と遷移確率",
      ],
      notes: "★47ページ★ 院試最頻出。§1-2は必ず使いこなせるように。",
    },
    {
      id: 10,
      title: "WKB法（準古典的近似法）",
      startPage: 367,
      endPage: 383,
      week: 10,
      importance: 3,
      gap: "中",
      sections: [
        { id: "10-1", title: "量子力学より古典力学への移行", startPage: 368, endPage: 368 },
        { id: "10-2", title: "準古典近似", startPage: 368, endPage: 369 },
        { id: "10-3", title: "接続公式", startPage: 370, endPage: 373 },
        { id: "10-4", title: "Bohr-Sommerfeldの量子条件", startPage: 374, endPage: 375 },
        { id: "10-5", title: "ポテンシャルの壁を透過する確率", startPage: 376, endPage: 383 },
      ],
      examTopics: [
        "WKB近似のトンネル透過率",
        "Bohr-Sommerfeld量子条件",
      ],
      notes: "17ページ。短いが概念は重要。1次元問題と組み合わせて出る。",
    },
    {
      id: 11,
      title: "同種粒子",
      startPage: 384,
      endPage: 424,
      week: 10,
      importance: 4,
      gap: "大",
      sections: [
        { id: "11-1", title: "フェルミオンとボソン", startPage: 385, endPage: 388 },
        { id: "11-2", title: "簡単な例", startPage: 389, endPage: 397 },
        { id: "11-3", title: "第二量子化", startPage: 398, endPage: 424 },
      ],
      examTopics: [
        "対称・反対称波動関数の構成",
        "Pauli原理の応用",
        "第二量子化（生成・消滅演算子）",
      ],
      notes: "41ページ。§3の第二量子化は場の量子論への橋渡し。",
    },
    {
      id: 12,
      title: "散乱問題",
      startPage: 425,
      endPage: 472,
      week: 11,
      importance: 5,
      gap: "大",
      sections: [
        { id: "12-1", title: "散乱断面積", startPage: 426, endPage: 427 },
        { id: "12-2", title: "散乱断面積の計算", startPage: 428, endPage: 432 },
        { id: "12-3", title: "散乱状態の波動関数に対する積分方程式", startPage: 433, endPage: 434 },
        { id: "12-4", title: "Born近似", startPage: 435, endPage: 439 },
        { id: "12-5", title: "部分波と位相のずれ", startPage: 440, endPage: 448 },
        { id: "12-6", title: "いくつかの応用", startPage: 449, endPage: 453 },
        { id: "12-7", title: "Coulomb散乱", startPage: 454, endPage: 455 },
        { id: "12-8", title: "同種粒子の散乱", startPage: 456, endPage: 457 },
        { id: "12-9", title: "Lippmann-Schwinger方程式", startPage: 458, endPage: 472 },
      ],
      examTopics: [
        "Born近似による散乱断面積の計算",
        "部分波展開と位相のずれ",
        "光学定理",
        "Lippmann-Schwinger方程式",
      ],
      notes: "★48ページ★ 院試頻出。§4 Born近似と§5 部分波は必須。",
    },
    {
      id: 13,
      title: "原子・分子・原子核・素粒子",
      startPage: 473,
      endPage: 522,
      week: 12,
      importance: 3,
      gap: "大",
      sections: [
        { id: "13-1", title: "2電子原子：ヘリウム原子の基底状態", startPage: 474, endPage: 477 },
        { id: "13-2", title: "ヘリウム原子の励起状態", startPage: 478, endPage: 480 },
        { id: "13-3", title: "多電子原子", startPage: 481, endPage: 483 },
        { id: "13-4", title: "Hartree近似", startPage: 484, endPage: 485 },
        { id: "13-5", title: "1電子原子：スピン軌道相互作用と微細構造", startPage: 486, endPage: 492 },
        { id: "13-6", title: "外部磁場中の原子スペクトル", startPage: 493, endPage: 499 },
        { id: "13-7", title: "Born-Oppenheimerの方法", startPage: 500, endPage: 504 },
        { id: "13-8", title: "原子核の殻模型", startPage: 505, endPage: 507 },
        { id: "13-9", title: "素粒子の模型", startPage: 508, endPage: 522 },
      ],
      examTopics: [
        "ヘリウム原子の変分法",
        "スピン軌道相互作用",
        "Zeeman効果",
      ],
      notes: "50ページ。§1-2ヘリウムと§5-6が特に出やすい。",
    },
    {
      id: 14,
      title: "電磁場の量子化",
      startPage: 523,
      endPage: 565,
      week: 14,
      importance: 3,
      gap: "大",
      sections: [
        { id: "14-1", title: "スカラー場の量子化", startPage: 524, endPage: 533 },
        { id: "14-2", title: "電磁場の自由度", startPage: 534, endPage: 540 },
        { id: "14-3", title: "自由な電磁場の量子化", startPage: 541, endPage: 542 },
        { id: "14-4", title: "物質と電磁場の相互作用", startPage: 543, endPage: 548 },
        { id: "14-5", title: "光の吸収・放出に関するEinsteinの関係式", startPage: 549, endPage: 552 },
        { id: "14-6", title: "双極子輻射", startPage: 553, endPage: 565 },
      ],
      examTopics: [
        "光子の生成・消滅演算子",
        "自然放出・誘導放出",
        "選択則",
      ],
      notes: "43ページ。場の量子論への入口。余裕があれば。",
    },
    {
      id: 15,
      title: "Dirac方程式",
      startPage: 566,
      endPage: 594,
      week: 15,
      importance: 2,
      gap: "大",
      sections: [
        { id: "15-1", title: "共変なスピノル場", startPage: 567, endPage: 571 },
        { id: "15-2", title: "Dirac方程式", startPage: 572, endPage: 574 },
        { id: "15-3", title: "粒子と反粒子", startPage: 575, endPage: 594 },
      ],
      examTopics: [
        "Dirac方程式の導出と性質",
      ],
      notes: "29ページ。発展的内容。余裕があれば。",
    },
    {
      id: 16,
      title: "経路積分",
      startPage: 595,
      endPage: 606,
      week: 16,
      importance: 2,
      gap: "大",
      sections: [
        { id: "16-1", title: "最小作用の原理と経路積分", startPage: 596, endPage: 599 },
        { id: "16-2", title: "正準形式と経路積分", startPage: 600, endPage: 606 },
      ],
      examTopics: [
        "経路積分の概念",
      ],
      notes: "12ページ。最短章。概要だけ読む。",
    },
  ],

  appendices: [
    { id: "A", title: "付録A　特殊関数", startPage: 278, endPage: 285 },
    { id: "B", title: "付録B　曲線座標におけるラプラシアン", startPage: 286, endPage: 289 },
    { id: "C", title: "付録C　Airy関数", startPage: 607, endPage: 609 },
  ],

  weekPlan: [
    { week: 1, chapters: [1, 2], pages: "p.1-47", focus: "量子論の基礎とSchrödinger方程式", pace: "1章は速読→2章は丁寧に" },
    { week: 2, chapters: [3], pages: "p.48-70", focus: "1次元量子系（前半：§1-6）", pace: "★頻出★ 全例題を手で解く" },
    { week: 3, chapters: [3, 4], pages: "p.70-122", focus: "1次元量子系（後半）+ 基本的性質", pace: "3章の章末問題→4章へ" },
    { week: 4, chapters: [5], pages: "p.123-169", focus: "中心力場のSchrödinger方程式", pace: "★超頻出★ 水素原子を完全に" },
    { week: 5, chapters: [6], pages: "p.170-215", focus: "量子力学の体系", pace: "ブラケット・生成消滅演算子が核心" },
    { week: 6, chapters: [7], pages: "p.216-260", focus: "角運動量と対称性（前半：§1-6）", pace: "★最重要★ じっくり" },
    { week: 7, chapters: [7], pages: "p.258-290", focus: "角運動量（後半）+ 付録A,B", pace: "§6合成は必須" },
    { week: 8, chapters: [8], pages: "p.291-319", focus: "磁場中の荷電粒子", pace: "Landau準位とAB効果を丁寧に" },
    { week: 9, chapters: [9], pages: "p.320-355", focus: "摂動論（§1-5）", pace: "★最重要★ 非縮退・縮退摂動を完全に" },
    { week: 10, chapters: [9, 10, 11], pages: "p.356-424", focus: "摂動論（後半）+ WKB + 同種粒子", pace: "Fermiの黄金律・第二量子化" },
    { week: 11, chapters: [12], pages: "p.425-472", focus: "散乱問題", pace: "★頻出★ Born近似と部分波展開" },
    { week: 12, chapters: [13], pages: "p.473-522", focus: "原子・分子・原子核・素粒子", pace: "ヘリウム原子とZeeman効果が中心" },
    { week: 13, chapters: [], pages: "", focus: "Vol.I 総復習 + 過去問演習（1-7章）", pace: "1-7章の章末問題を重点的に" },
    { week: 14, chapters: [14], pages: "p.523-565", focus: "電磁場の量子化", pace: "余裕があれば。なければ概要のみ" },
    { week: 15, chapters: [15], pages: "p.566-594", focus: "Dirac方程式", pace: "余裕があれば。なければ概要のみ" },
    { week: 16, chapters: [16], pages: "p.595-610", focus: "経路積分 + Vol.II 総復習・過去問演習", pace: "仕上げ" },
  ],

  examInfo: {
    description: "東大理物の第2問は毎年量子力学。1体問題・角運動量・摂動論・散乱が頻出。",
    frequentTopics: [
      { theme: "1次元ポテンシャル問題（トンネル・井戸型）", ch: [3], freq: 5 },
      { theme: "水素原子・中心力場", ch: [5], freq: 5 },
      { theme: "角運動量の合成・スピン", ch: [7], freq: 5 },
      { theme: "調和振動子（生成消滅演算子）", ch: [3, 6], freq: 5 },
      { theme: "非縮退・縮退摂動論", ch: [9], freq: 5 },
      { theme: "Born近似・部分波展開", ch: [12], freq: 5 },
      { theme: "不確定性関係・交換関係", ch: [4, 6], freq: 4 },
      { theme: "Fermiの黄金律・遷移確率", ch: [9], freq: 4 },
      { theme: "Landau準位", ch: [8], freq: 4 },
      { theme: "ヘリウム原子（変分法）", ch: [13], freq: 4 },
      { theme: "Heisenberg描像での計算", ch: [6], freq: 3 },
      { theme: "WKB近似", ch: [10], freq: 3 },
      { theme: "第二量子化", ch: [11], freq: 3 },
      { theme: "Zeeman効果", ch: [13], freq: 3 },
    ],
    relatedExams: [],
  },
};
