// 砂川重信『理論電磁気学』第3版
export default {
  id: "sunakawa-emag",
  title: "理論電磁気学",
  author: "砂川重信",
  edition: "第3版",
  subtitle: "東大理物 院試 + 一陸技",
  totalPages: 459,
  weekCount: 10,
  defaultStartDate: "2026-02-24",

  chapters: [
    {
      id: 1,
      title: "真空電磁場の基本法則",
      startPage: 1,
      endPage: 27,
      week: 1,
      importance: 3,
      gap: "小",
      sections: [
        { id: "1-1", title: "場の概念", startPage: 1, endPage: 3 },
        { id: "1-2", title: "電場と磁場の定義", startPage: 4, endPage: 5 },
        { id: "1-3", title: "Coulombの法則", startPage: 6, endPage: 13 },
        { id: "1-4", title: "Faradayの電磁誘導の法則", startPage: 14, endPage: 17 },
        { id: "1-5", title: "Ampèreの法則", startPage: 18, endPage: 18 },
        { id: "1-6", title: "電荷保存則と変位電流", startPage: 19, endPage: 21 },
        { id: "1-7", title: "Maxwellの方程式", startPage: 22, endPage: 27 },
      ],
      examTopics: ["Maxwell方程式の導出は直接出ないが全ての基礎"],
      notes: "復習感覚で速読OK。工学で既習の内容が多い。",
    },
    {
      id: 2,
      title: "Maxwellの方程式の一般的性質",
      startPage: 28,
      endPage: 60,
      week: 1,
      importance: 4,
      gap: "中",
      sections: [
        { id: "2-1", title: "点電荷と電磁場との共存する体系", startPage: 28, endPage: 35 },
        { id: "2-2", title: "座標変換と時間反転", startPage: 36, endPage: 43 },
        { id: "2-3", title: "電磁ポテンシァルとゲージ変換", startPage: 44, endPage: 50 },
        { id: "2-4", title: "エネルギー保存則", startPage: 51, endPage: 54 },
        { id: "2-5", title: "運動量保存則", startPage: 55, endPage: 60 },
      ],
      examTopics: [
        "ゲージ変換（クーロンゲージ/ローレンツゲージ）",
        "ポインティングベクトル",
        "Maxwellの応力テンソル",
      ],
      notes: "ゲージ変換は量子力学でも重要。丁寧に理解する価値あり。",
    },
    {
      id: 3,
      title: "静止物体中のMaxwellの方程式",
      startPage: 61,
      endPage: 79,
      week: 2,
      importance: 4,
      gap: "中",
      sections: [
        { id: "3-1", title: "静止物体中の電磁場", startPage: 61, endPage: 62 },
        { id: "3-2", title: "物質中のMaxwellの方程式", startPage: 63, endPage: 68 },
        { id: "3-3", title: "Ohmの法則", startPage: 69, endPage: 74 },
        { id: "3-4", title: "エネルギー保存則", startPage: 75, endPage: 79 },
      ],
      examTopics: [
        "誘電体・磁性体中の境界条件",
        "物質中のエネルギー密度",
      ],
      notes: "19ページと薄い章。工学の知識で速く読める。",
    },
    {
      id: 4,
      title: "静電場",
      startPage: 81,
      endPage: 125,
      week: 3,
      importance: 4,
      gap: "小〜中",
      sections: [
        { id: "4-1", title: "静電場の基本方程式", startPage: 81, endPage: 82 },
        { id: "4-2", title: "電荷分布による静電場", startPage: 83, endPage: 84 },
        { id: "4-3", title: "静電場の多重極展開", startPage: 85, endPage: 87 },
        { id: "4-4", title: "静電場のエネルギー", startPage: 88, endPage: 91 },
        { id: "4-5", title: "導体系の静電場", startPage: 92, endPage: 97 },
        { id: "4-6", title: "誘電体中のGaussの法則", startPage: 98, endPage: 105 },
        { id: "4-7", title: "誘電体の境界条件", startPage: 106, endPage: 109 },
        { id: "4-8", title: "境界値問題", startPage: 110, endPage: 125 },
      ],
      examTopics: [
        "境界値問題（球座標・円筒座標）",
        "鏡像法",
        "多重極展開（双極子・四重極）",
        "グリーン関数法",
      ],
      notes: "45ページの大章。院試頻出。例題を手で解くこと。§8が最重要。",
    },
    {
      id: 5,
      title: "定常電流",
      startPage: 127,
      endPage: 150,
      week: 5,
      importance: 2,
      gap: "小",
      sections: [
        { id: "5-1", title: "定常電流の基本法則", startPage: 127, endPage: 127 },
        { id: "5-2", title: "定常電流による静磁場の決定", startPage: 128, endPage: 132 },
        { id: "5-3", title: "ベクトル・ポテンシァルの多重極展開", startPage: 133, endPage: 139 },
        { id: "5-4", title: "定常電流による磁場のエネルギー", startPage: 140, endPage: 141 },
        { id: "5-5", title: "定常電流の分布", startPage: 142, endPage: 146 },
        { id: "5-6", title: "Joule熱最小の定理", startPage: 147, endPage: 150 },
      ],
      examTopics: ["ベクトルポテンシャルの多重極展開", "単独では出にくい"],
      notes: "24ページ。軽めだが§3の多重極展開は放射の章で再登場する。",
    },
    {
      id: 6,
      title: "静磁場",
      startPage: 152,
      endPage: 167,
      week: 5,
      importance: 3,
      gap: "小",
      sections: [
        { id: "6-1", title: "静磁場の基本方程式", startPage: 152, endPage: 153 },
        { id: "6-2", title: "永久磁化", startPage: 154, endPage: 154 },
        { id: "6-3", title: "境界条件", startPage: 155, endPage: 160 },
        { id: "6-4", title: "物質の磁性", startPage: 161, endPage: 167 },
      ],
      examTopics: [
        "磁性体の境界条件",
        "磁気双極子モーメント",
      ],
      notes: "16ページ。最も薄い章。5章と合わせて1週間で終わる。",
    },
    {
      id: 7,
      title: "準定常電流",
      startPage: 168,
      endPage: 184,
      week: 6,
      importance: 2,
      gap: "小",
      sections: [
        { id: "7-1", title: "準定常電流の基本法則", startPage: 168, endPage: 171 },
        { id: "7-2", title: "線状回路", startPage: 172, endPage: 178 },
        { id: "7-3", title: "準定常電流の空間的分布", startPage: 179, endPage: 184 },
      ],
      examTopics: ["同軸ケーブル等の問題で出ることがある", "表皮効果"],
      notes: "17ページ。工学で十分やっている。速読でOK。",
    },
    {
      id: 8,
      title: "電磁波",
      startPage: 185,
      endPage: 248,
      week: 6,
      importance: 5,
      gap: "大",
      sections: [
        { id: "8-1", title: "真空中の電磁波の基本法則", startPage: 185, endPage: 186 },
        { id: "8-2", title: "真空中の電磁波", startPage: 187, endPage: 197 },
        { id: "8-3", title: "誘電体中の電磁波", startPage: 198, endPage: 209 },
        { id: "8-4", title: "電磁波の反射と屈折", startPage: 210, endPage: 216 },
        { id: "8-5", title: "導体中の電磁波", startPage: 217, endPage: 220 },
        { id: "8-6", title: "電磁波の回折", startPage: 221, endPage: 231 },
        { id: "8-7", title: "電磁波の散乱", startPage: 232, endPage: 248 },
      ],
      examTopics: [
        "反射・屈折（フレネルの式）",
        "偏光（ブリュースター角）",
        "導体表面での反射・表皮深さ",
        "回折（キルヒホッフ・フラウンホーファー）",
        "散乱（トムソン・レイリー散乱）",
      ],
      notes: "★64ページの最大章★ 院試最頻出。2週間かけてじっくり。一陸技の工学Bにも直結。",
    },
    {
      id: 9,
      title: "電磁波の放射",
      startPage: 251,
      endPage: 312,
      week: 8,
      importance: 5,
      gap: "大",
      sections: [
        { id: "9-1", title: "遅延ポテンシァルと先進ポテンシァル", startPage: 251, endPage: 256 },
        { id: "9-2", title: "多重極放射", startPage: 257, endPage: 272 },
        { id: "9-3", title: "点電荷による電磁波の放射", startPage: 273, endPage: 294 },
        { id: "9-4", title: "点電荷による電磁波の散乱", startPage: 295, endPage: 299 },
        { id: "9-5", title: "電磁波の放射の反作用", startPage: 300, endPage: 312 },
      ],
      examTopics: [
        "遅延ポテンシャルの導出と物理的意味",
        "電気双極子放射のパターンとパワー",
        "リエナール・ヴィーヘルトポテンシャル",
        "ラーモアの公式",
        "トムソン散乱・コンプトン散乱",
        "放射の反作用（Abraham-Lorentz力）",
      ],
      notes: "★62ページ★ 院試最頻出。§2双極子放射と§3点電荷放射は必ず解けるように。",
    },
    {
      id: 10,
      title: "運動物体の電磁気学",
      startPage: 314,
      endPage: 346,
      week: 9,
      importance: 3,
      gap: "大",
      sections: [
        { id: "10-1", title: "Hertzの理論", startPage: 314, endPage: 319 },
        { id: "10-2", title: "Galileiの相対性原理", startPage: 320, endPage: 323 },
        { id: "10-3", title: "Hertzの方程式と実験事実との比較", startPage: 324, endPage: 325 },
        { id: "10-4", title: "Lorentzの理論", startPage: 326, endPage: 339 },
        { id: "10-5", title: "Michelson-Morleyの実験", startPage: 340, endPage: 346 },
      ],
      examTopics: [
        "ローレンツ変換の導出",
        "電磁場のローレンツ変換",
      ],
      notes: "歴史的な導入から特殊相対論へ。11章と一体で読む。",
    },
    {
      id: 11,
      title: "特殊相対論",
      startPage: 347,
      endPage: 408,
      week: 9,
      importance: 3,
      gap: "大",
      sections: [
        { id: "11-1", title: "特殊相対論における時間と空間", startPage: 347, endPage: 364 },
        { id: "11-2", title: "Maxwellの方程式のLorentz変換", startPage: 365, endPage: 372 },
        { id: "11-3", title: "テンソルと共変性", startPage: 373, endPage: 389 },
        { id: "11-4", title: "相対性力学", startPage: 390, endPage: 401 },
        { id: "11-5", title: "電磁波の放射の反作用と共変性", startPage: 402, endPage: 408 },
      ],
      examTopics: [
        "4元形式でのMaxwell方程式",
        "電磁場テンソルの成分",
        "4元運動量・エネルギー",
      ],
      notes: "62ページ。場の量子論への橋渡し。§3テンソルと共変性が核心。",
    },
    {
      id: 12,
      title: "電磁場と変分原理",
      startPage: 410,
      endPage: 436,
      week: 10,
      importance: 2,
      gap: "大",
      sections: [
        { id: "12-1", title: "古典力学と変分原理", startPage: 410, endPage: 415 },
        { id: "12-2", title: "点電荷と電磁場の共存系", startPage: 416, endPage: 436 },
      ],
      examTopics: ["直接は出にくいが、解析力学・場の量子論への接続"],
      notes: "27ページ。余裕があれば。なければ概要だけ読む。",
    },
  ],

  appendices: [
    { id: "A", title: "付録A　初等ベクトル解析", startPage: 437, endPage: 450 },
    { id: "B", title: "付録B　直交関数系", startPage: 451, endPage: 458 },
  ],

  weekPlan: [
    { week: 1, chapters: [1, 2], pages: "p.1-60", focus: "Maxwell方程式の基礎と一般的性質", pace: "1章は速読→2章は丁寧に" },
    { week: 2, chapters: [3], pages: "p.61-79", focus: "物質中のMaxwell方程式", pace: "19pなので余裕あり。付録Aも確認" },
    { week: 3, chapters: [4], pages: "p.81-105", focus: "静電場（前半：§1-6）", pace: "例題を手で解く" },
    { week: 4, chapters: [4], pages: "p.106-125", focus: "静電場（後半：§7-8 境界値問題）", pace: "院試頻出！§8は特に丁寧に" },
    { week: 5, chapters: [5, 6], pages: "p.127-167", focus: "定常電流・静磁場", pace: "40pを1週で。比較的軽め" },
    { week: 6, chapters: [7, 8], pages: "p.168-220", focus: "準定常電流 → 電磁波（§1-5）", pace: "7章速読、8章§4反射屈折が山場" },
    { week: 7, chapters: [8], pages: "p.221-248", focus: "電磁波（§6-7：回折・散乱）", pace: "★最重要★ 過去問と照合" },
    { week: 8, chapters: [9], pages: "p.251-312", focus: "電磁波の放射", pace: "★最重要★ 62pをじっくり" },
    { week: 9, chapters: [10, 11], pages: "p.314-408", focus: "相対論的電磁気学", pace: "95p。新しい内容多い。飛ばす節も判断" },
    { week: 10, chapters: [12], pages: "p.410-436", focus: "変分原理 + 総復習・過去問演習", pace: "仕上げ。付録Bも確認" },
  ],

  examInfo: {
    description: "東大理物の第3問は毎年電磁気学。miyake.github.io と phys.s.u-tokyo.ac.jp で過去問入手可。",
    frequentTopics: [
      { theme: "電磁波の反射・屈折（フレネルの式）", ch: [8], freq: 5 },
      { theme: "電気双極子放射", ch: [9], freq: 5 },
      { theme: "電磁波の回折（キルヒホッフ）", ch: [8], freq: 4 },
      { theme: "遅延ポテンシャル", ch: [9], freq: 4 },
      { theme: "境界値問題（Laplace方程式）", ch: [4], freq: 4 },
      { theme: "散乱（トムソン・レイリー）", ch: [8, 9], freq: 4 },
      { theme: "多重極展開", ch: [4, 5], freq: 3 },
      { theme: "ポインティングベクトル", ch: [2, 8], freq: 3 },
      { theme: "導体中の電磁波・表皮効果", ch: [8], freq: 3 },
      { theme: "リエナール・ヴィーヘルトポテンシャル", ch: [9], freq: 3 },
      { theme: "電磁場のローレンツ変換", ch: [10, 11], freq: 2 },
      { theme: "電磁場テンソル", ch: [11], freq: 2 },
    ],
    relatedExams: [
      { subject: "無線工学の基礎", coverage: "1-6章", match: 4, note: "回路理論・電磁気の基礎" },
      { subject: "無線工学A", coverage: "範囲外", match: 1, note: "送受信機等。別途対策必要" },
      { subject: "無線工学B", coverage: "8-9章", match: 5, note: "電磁波・アンテナ・放射が直結" },
      { subject: "法規", coverage: "範囲外", match: 0, note: "電波法。暗記で対処" },
    ],
  },
};
