import type { Book } from "../types.ts";

// 熱力学・統計力学（東大理物 院試対策）
export default {
	id: "thermo-stat",
	category: "物理",
	title: "熱力学・統計力学",
	author: "久保亮五 編",
	edition: "初版",
	subtitle: "東大理物 院試",
	totalPages: 492,
	weekCount: 10,
	defaultStartDate: "2026-02-24",

	chapters: [
		{
			id: 1,
			title: "熱力学的状態，熱力学第1法則",
			startPage: 1,
			endPage: 40,
			week: 1,
			importance: 4,
			gap: "小〜中",
			sections: [
				{ id: "1-1", title: "熱力学の対象", startPage: 1, endPage: 1 },
				{ id: "1-2", title: "熱平衡の概念（熱力学第0法則）", startPage: 1, endPage: 1 },
				{ id: "1-3", title: "熱力学的な接触", startPage: 2, endPage: 2 },
				{ id: "1-4", title: "熱力学的な量", startPage: 3, endPage: 3 },
				{ id: "1-5", title: "変化の過程", startPage: 3, endPage: 3 },
				{ id: "1-6", title: "熱力学第1法則", startPage: 4, endPage: 5 },
				{ id: "1-7", title: "熱量", startPage: 6, endPage: 6 },
				{ id: "1-8", title: "無限小過程についての熱力学第1法則", startPage: 6, endPage: 7 },
				{ id: "1-9", title: "温度", startPage: 8, endPage: 8 },
				{ id: "1-10", title: "熱容量，比熱", startPage: 8, endPage: 8 },
				{ id: "1-11", title: "状態方程式", startPage: 8, endPage: 11 },
				{ id: "1-12", title: "独立変数の変更", startPage: 12, endPage: 40 },
			],
			examTopics: ["状態方程式からの熱力学量の導出", "熱容量の関係式", "独立変数の変更とJacobianの利用"],
			notes: "40ページ。基礎事項+例題+演習。例題を全て解くこと。",
		},
		{
			id: 2,
			title: "熱力学第2法則とエントロピー",
			startPage: 41,
			endPage: 87,
			week: 2,
			importance: 5,
			gap: "中",
			sections: [
				{ id: "2-1", title: "可逆過程と不可逆過程", startPage: 41, endPage: 41 },
				{ id: "2-2", title: "補助定理（Carnotサイクル）", startPage: 42, endPage: 42 },
				{ id: "2-3", title: "熱力学第2法則", startPage: 42, endPage: 42 },
				{ id: "2-4", title: "一般的なCarnotサイクルの効率", startPage: 43, endPage: 43 },
				{ id: "2-5", title: "絶対温度", startPage: 44, endPage: 45 },
				{ id: "2-6", title: "任意のサイクルに関するClausiusの不等式", startPage: 46, endPage: 46 },
				{ id: "2-7", title: "エントロピー", startPage: 46, endPage: 47 },
				{ id: "2-8", title: "エントロピーの相加性", startPage: 48, endPage: 48 },
				{ id: "2-9", title: "第2法則の一般的表現", startPage: 49, endPage: 49 },
				{ id: "2-10", title: "実際に起こる変化の向き", startPage: 50, endPage: 50 },
				{ id: "2-11", title: "最大仕事と最小仕事", startPage: 51, endPage: 87 },
			],
			examTopics: [
				"Carnotサイクルの効率",
				"エントロピーの計算",
				"Clausiusの不等式の応用",
				"不可逆過程のエントロピー変化",
			],
			notes: "★47ページ★ 第2法則は熱力学の核心。例題を全て手で解く。",
		},
		{
			id: 3,
			title: "熱力学関数と平衡条件",
			startPage: 88,
			endPage: 127,
			week: 3,
			importance: 5,
			gap: "中",
			sections: [
				{ id: "3-1", title: "熱力学関数", startPage: 88, endPage: 89 },
				{ id: "3-2", title: "Legendre変換", startPage: 90, endPage: 90 },
				{ id: "3-3", title: "Gibbs-Duhemの関係", startPage: 91, endPage: 91 },
				{ id: "3-4", title: "若干の熱力学的量の定義および熱力学関係式", startPage: 91, endPage: 92 },
				{ id: "3-5", title: "熱力学第3法則（Nernst-Planckの定理）", startPage: 93, endPage: 93 },
				{ id: "3-6", title: "二つの系の間の平衡", startPage: 94, endPage: 94 },
				{ id: "3-7", title: "与えられた環境のもとにおける熱平衡条件", startPage: 94, endPage: 95 },
				{ id: "3-8", title: "熱力学の不等式", startPage: 96, endPage: 97 },
				{ id: "3-9", title: "Le Chatelier-Braunの原理", startPage: 98, endPage: 127 },
			],
			examTopics: [
				"自由エネルギー・Gibbsエネルギーの計算",
				"Maxwellの関係式",
				"Legendre変換",
				"平衡条件と安定性",
				"Le Chatelier-Braunの原理",
			],
			notes: "★40ページ★ 院試最頻出。Maxwellの関係式は暗記レベル。",
		},
		{
			id: 4,
			title: "相平衡および化学平衡",
			startPage: 128,
			endPage: 193,
			week: 4,
			importance: 4,
			gap: "中〜大",
			sections: [
				{ id: "4-1", title: "相", startPage: 128, endPage: 128 },
				{ id: "4-2", title: "純粋物質の異なる相の間の平衡", startPage: 128, endPage: 129 },
				{ id: "4-3", title: "表面張力", startPage: 130, endPage: 130 },
				{ id: "4-4", title: "異なる相にある多成分系の平衡", startPage: 130, endPage: 130 },
				{ id: "4-5", title: "Gibbsの相律", startPage: 131, endPage: 131 },
				{ id: "4-6", title: "気体の化学ポテンシャル", startPage: 132, endPage: 133 },
				{ id: "4-7", title: "液体および固体における化学ポテンシャル，飽和蒸気圧", startPage: 134, endPage: 134 },
				{ id: "4-8", title: "理想希薄溶液", startPage: 135, endPage: 135 },
				{ id: "4-9", title: "理想溶液と正則溶液", startPage: 136, endPage: 136 },
				{ id: "4-10", title: "溶液の濃度の表し方", startPage: 136, endPage: 137 },
				{ id: "4-11", title: "活動度および活動度係数", startPage: 137, endPage: 138 },
				{ id: "4-12", title: "強電解質溶液", startPage: 138, endPage: 139 },
				{ id: "4-13", title: "化学平衡", startPage: 140, endPage: 140 },
				{ id: "4-14", title: "電池の熱力学", startPage: 141, endPage: 142 },
				{ id: "4-15", title: "熱力学第3法則の応用", startPage: 143, endPage: 193 },
			],
			examTopics: ["Clausius-Clapeyronの式", "相律の応用", "化学ポテンシャルの計算", "相転移（1次・2次）"],
			notes: "66ページの大章。相転移の問題は頻出。例題を丁寧に。",
		},
		{
			id: 5,
			title: "統計力学の原理",
			startPage: 194,
			endPage: 267,
			week: 5,
			importance: 5,
			gap: "大",
			sections: [
				{ id: "5-1", title: "微視的状態", startPage: 194, endPage: 195 },
				{ id: "5-2", title: "統計力学的な見方", startPage: 196, endPage: 197 },
				{ id: "5-3", title: "等重率の原理とミクロカノニカル集団", startPage: 198, endPage: 199 },
				{ id: "5-4", title: "巨視的状態の熱力学的重率とエントロピー", startPage: 200, endPage: 200 },
				{ id: "5-5", title: "状態数および状態密度", startPage: 200, endPage: 201 },
				{ id: "5-6", title: "統計熱力学的に正常な系", startPage: 202, endPage: 203 },
				{ id: "5-7", title: "二つの系の接触", startPage: 204, endPage: 204 },
				{ id: "5-8", title: "準静的断熱過程", startPage: 205, endPage: 205 },
				{ id: "5-9", title: "接触する二つの系の平衡", startPage: 206, endPage: 208 },
				{ id: "5-10", title: "熱力学の基本法則", startPage: 209, endPage: 210 },
				{ id: "5-11", title: "最も確からしい状態，ゆらぎ", startPage: 211, endPage: 211 },
				{ id: "5-12", title: "カノニカル分布", startPage: 211, endPage: 211 },
				{ id: "5-13", title: "一般的なカノニカル分布", startPage: 212, endPage: 213 },
				{ id: "5-14", title: "分配関数と熱力学関数", startPage: 214, endPage: 216 },
				{ id: "5-15", title: "Fermi統計，Bose統計，Boltzmann統計", startPage: 217, endPage: 219 },
				{ id: "5-16", title: "エントロピーの一般的な定義", startPage: 220, endPage: 267 },
			],
			examTopics: [
				"ミクロカノニカル集団の状態数計算",
				"カノニカル分布の導出と応用",
				"分配関数から熱力学量の導出",
				"Fermi分布・Bose分布の導出",
				"エントロピーの統計力学的定義",
			],
			notes: "★74ページの最大章★ 統計力学の基礎。§12-16が特に重要。",
		},
		{
			id: 6,
			title: "カノニカル分布の応用",
			startPage: 268,
			endPage: 323,
			week: 6,
			importance: 4,
			gap: "大",
			sections: [
				{ id: "6-1", title: "分配関数Z(β)の一般的性質", startPage: 268, endPage: 269 },
				{ id: "6-2", title: "大きい系についての漸近評価", startPage: 270, endPage: 271 },
				{ id: "6-3", title: "漸近評価と熱力学関数のLegendre変換", startPage: 272, endPage: 272 },
				{ id: "6-4", title: "大分配関数", startPage: 273, endPage: 273 },
				{ id: "6-5", title: "一般的なカノニカル分布に関する分配関数", startPage: 274, endPage: 274 },
				{ id: "6-6", title: "古典的位置分布関数", startPage: 274, endPage: 275 },
				{ id: "6-7", title: "密度行列", startPage: 275, endPage: 323 },
			],
			examTopics: [
				"分配関数の計算（具体的な系）",
				"大分配関数とグランドカノニカル集団",
				"鞍点法（漸近評価）",
				"密度行列",
			],
			notes: "56ページ。§4大分配関数は頻出。具体的な計算を練習。",
		},
		{
			id: 7,
			title: "気体の統計熱力学",
			startPage: 324,
			endPage: 356,
			week: 7,
			importance: 3,
			gap: "中",
			sections: [
				{ id: "7-1", title: "理想気体の分配関数", startPage: 324, endPage: 324 },
				{ id: "7-2", title: "気体分子の内部自由度と分配関数", startPage: 325, endPage: 327 },
				{ id: "7-3", title: "混合理想気体", startPage: 328, endPage: 328 },
				{ id: "7-4", title: "分子間相互作用", startPage: 328, endPage: 329 },
				{ id: "7-5", title: "クラスター展開", startPage: 329, endPage: 356 },
			],
			examTopics: ["理想気体の分配関数の計算", "内部自由度（回転・振動）の寄与", "ビリアル展開"],
			notes: "33ページ。理想気体は基本。§5クラスター展開は発展的。",
		},
		{
			id: 8,
			title: "Fermi統計とBose統計の応用",
			startPage: 357,
			endPage: 408,
			week: 8,
			importance: 5,
			gap: "大",
			sections: [
				{ id: "8-1", title: "Fermi統計の基本公式", startPage: 357, endPage: 357 },
				{ id: "8-2", title: "Fermi分布関数", startPage: 358, endPage: 361 },
				{ id: "8-3", title: "結晶体内電子のエネルギーバンド", startPage: 362, endPage: 362 },
				{ id: "8-4", title: "空孔", startPage: 362, endPage: 363 },
				{ id: "8-5", title: "半導体", startPage: 364, endPage: 365 },
				{ id: "8-6", title: "Bose統計，液体ヘリウム", startPage: 366, endPage: 408 },
			],
			examTopics: ["Fermi気体の低温展開（Sommerfeld展開）", "Bose-Einstein凝縮", "状態密度と熱力学量", "自由電子模型"],
			notes: "★52ページ★ 院試超頻出。Fermi気体とBEC は必須。",
		},
		{
			id: 9,
			title: "強い相互作用をもつ系",
			startPage: 409,
			endPage: 453,
			week: 9,
			importance: 4,
			gap: "大",
			sections: [
				{ id: "9-1", title: "分子場の近似", startPage: 409, endPage: 411 },
				{ id: "9-2", title: "Bragg-Williamsの近似", startPage: 412, endPage: 413 },
				{ id: "9-3", title: "協力現象", startPage: 414, endPage: 415 },
				{ id: "9-4", title: "平均ポテンシャル", startPage: 416, endPage: 416 },
				{ id: "9-5", title: "荷電粒子に対するDebye-Hückelの理論", startPage: 417, endPage: 418 },
				{ id: "9-6", title: "粒子系の分布関数", startPage: 419, endPage: 453 },
			],
			examTopics: ["平均場近似（Isingモデル）", "相転移と臨界指数", "Bragg-Williams近似"],
			notes: "45ページ。Isingモデル・相転移は頻出。",
		},
		{
			id: 10,
			title: "ゆらぎと運動論",
			startPage: 454,
			endPage: 492,
			week: 10,
			importance: 3,
			gap: "中〜大",
			sections: [
				{ id: "10-1", title: "ゆらぎ", startPage: 454, endPage: 454 },
				{ id: "10-2", title: "衝突数", startPage: 455, endPage: 455 },
				{ id: "10-3", title: "Boltzmannの輸送方程式", startPage: 456, endPage: 492 },
			],
			examTopics: ["エネルギーのゆらぎ", "Boltzmann方程式", "H定理"],
			notes: "39ページ。ゆらぎの計算は基本。Boltzmann方程式は発展的。",
		},
	],

	appendices: [],

	weekPlan: [
		{ week: 1, chapters: [1], pages: "p.1-40", focus: "熱力学第1法則", pace: "基礎事項+例題を全て解く" },
		{
			week: 2,
			chapters: [2],
			pages: "p.41-87",
			focus: "熱力学第2法則とエントロピー",
			pace: "★核心★ Carnotサイクルとエントロピー",
		},
		{
			week: 3,
			chapters: [3],
			pages: "p.88-127",
			focus: "熱力学関数と平衡条件",
			pace: "★最頻出★ Maxwell関係式を完全に",
		},
		{
			week: 4,
			chapters: [4],
			pages: "p.128-193",
			focus: "相平衡および化学平衡",
			pace: "66pの大章。Clausius-Clapeyronが重要",
		},
		{ week: 5, chapters: [5], pages: "p.194-267", focus: "統計力学の原理", pace: "★最重要★ 74pをじっくり" },
		{ week: 6, chapters: [6], pages: "p.268-323", focus: "カノニカル分布の応用", pace: "大分配関数と具体的な計算" },
		{ week: 7, chapters: [7], pages: "p.324-356", focus: "気体の統計熱力学", pace: "比較的軽め。分配関数の具体計算" },
		{ week: 8, chapters: [8], pages: "p.357-408", focus: "Fermi統計とBose統計の応用", pace: "★超頻出★ Fermi気体とBEC" },
		{ week: 9, chapters: [9], pages: "p.409-453", focus: "強い相互作用をもつ系", pace: "Isingモデル・相転移" },
		{ week: 10, chapters: [10], pages: "p.454-492", focus: "ゆらぎと運動論 + 総復習", pace: "仕上げ。過去問演習" },
	],

	examInfo: {
		description: "東大理物の第1問は毎年熱力学・統計力学。熱力学の基本から量子統計まで幅広く出題。",
		frequentTopics: [
			{ theme: "エントロピーの計算・不可逆過程", ch: [2], freq: 5 },
			{ theme: "熱力学関数とMaxwellの関係式", ch: [3], freq: 5 },
			{ theme: "Fermi気体（Sommerfeld展開）", ch: [8], freq: 5 },
			{ theme: "Bose-Einstein凝縮", ch: [8], freq: 5 },
			{ theme: "分配関数の計算と熱力学量", ch: [5, 6], freq: 5 },
			{ theme: "相転移（Clausius-Clapeyron）", ch: [4], freq: 4 },
			{ theme: "Isingモデル・平均場", ch: [9], freq: 4 },
			{ theme: "カノニカル分布の応用", ch: [6], freq: 4 },
			{ theme: "理想気体の統計力学", ch: [7], freq: 3 },
			{ theme: "ゆらぎ（エネルギーのゆらぎ等）", ch: [10], freq: 3 },
			{ theme: "大分配関数", ch: [6], freq: 3 },
			{ theme: "熱容量の計算", ch: [1, 5], freq: 3 },
		],
		relatedExams: [],
	},
} satisfies Book;
