import type { Book } from "../types.ts";

// ウォーレン有機化学（上巻+下巻）第2版
export default {
	id: "warren-organic",
	category: "化学",
	title: "ウォーレン有機化学",
	author: "Clayden, Greeves, Warren",
	edition: "第2版",
	subtitle: "",
	totalPages: 1360,
	weekCount: 0,
	defaultStartDate: "2026-02-24",

	chapters: [
		// ── 上巻 ──
		{
			id: 1,
			title: "有機化学とは何か",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "1", title: "有機化学とは何か", startPage: 0, endPage: 0 }],
		},
		{
			id: 2,
			title: "有機化合物の構造",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "2", title: "有機化合物の構造", startPage: 0, endPage: 0 }],
		},
		{
			id: 3,
			title: "有機化合物の構造決定",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "3", title: "有機化合物の構造決定", startPage: 0, endPage: 0 }],
		},
		{
			id: 4,
			title: "分子の構造",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "4", title: "分子の構造", startPage: 0, endPage: 0 }],
		},
		{
			id: 5,
			title: "有機反応",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "5", title: "有機反応", startPage: 0, endPage: 0 }],
		},
		{
			id: 6,
			title: "カルボニル基への求核付加反応",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "6", title: "カルボニル基への求核付加反応", startPage: 0, endPage: 0 }],
		},
		{
			id: 7,
			title: "非局在化と共役",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "7", title: "非局在化と共役", startPage: 0, endPage: 0 }],
		},
		{
			id: 8,
			title: "酸性度と塩基性度",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "8", title: "酸性度と塩基性度", startPage: 0, endPage: 0 }],
		},
		{
			id: 9,
			title: "有機金属化合物を用いる炭素-炭素結合の生成",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "9", title: "有機金属化合物を用いる炭素-炭素結合の生成", startPage: 0, endPage: 0 }],
		},
		{
			id: 10,
			title: "カルボニル基での求核置換反応",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "10", title: "カルボニル基での求核置換反応", startPage: 0, endPage: 0 }],
		},
		{
			id: 11,
			title: "カルボニル酸素の消失を伴うカルボニル基での求核置換反応",
			startPage: 0,
			endPage: 0,
			sections: [
				{ id: "11", title: "カルボニル酸素の消失を伴うカルボニル基での求核置換反応", startPage: 0, endPage: 0 },
			],
		},
		{
			id: 12,
			title: "平衡，反応速度，および反応機構",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "12", title: "平衡，反応速度，および反応機構", startPage: 0, endPage: 0 }],
		},
		{
			id: 13,
			title: "プロトンNMR",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "13", title: "プロトンNMR", startPage: 0, endPage: 0 }],
		},
		{
			id: 14,
			title: "立体化学",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "14", title: "立体化学", startPage: 0, endPage: 0 }],
		},
		{
			id: 15,
			title: "飽和炭素での求核置換反応",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "15", title: "飽和炭素での求核置換反応", startPage: 0, endPage: 0 }],
		},
		{
			id: 16,
			title: "立体配座解析",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "16", title: "立体配座解析", startPage: 0, endPage: 0 }],
		},
		{
			id: 17,
			title: "脱離反応",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "17", title: "脱離反応", startPage: 0, endPage: 0 }],
		},
		{
			id: 18,
			title: "分光法のまとめ",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "18", title: "分光法のまとめ", startPage: 0, endPage: 0 }],
		},
		{
			id: 19,
			title: "アルケンへの求電子付加反応",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "19", title: "アルケンへの求電子付加反応", startPage: 0, endPage: 0 }],
		},
		{
			id: 20,
			title: "エノールおよびエノラートの生成と反応",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "20", title: "エノールおよびエノラートの生成と反応", startPage: 0, endPage: 0 }],
		},
		{
			id: 21,
			title: "芳香族求電子置換反応",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "21", title: "芳香族求電子置換反応", startPage: 0, endPage: 0 }],
		},
		{
			id: 22,
			title: "共役付加と芳香族求核置換反応",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "22", title: "共役付加と芳香族求核置換反応", startPage: 0, endPage: 0 }],
		},
		{
			id: 23,
			title: "官能基選択性と保護基",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "23", title: "官能基選択性と保護基", startPage: 0, endPage: 0 }],
		},
		{
			id: 24,
			title: "位置選択性",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "24", title: "位置選択性", startPage: 0, endPage: 0 }],
		},
		{
			id: 25,
			title: "エノラートのアルキル化",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "25", title: "エノラートのアルキル化", startPage: 0, endPage: 0 }],
		},
		{
			id: 26,
			title: "エノラートとカルボニル化合物との反応：アルドール反応とClaisen縮合",
			startPage: 0,
			endPage: 0,
			sections: [
				{
					id: "26",
					title: "エノラートとカルボニル化合物との反応：アルドール反応とClaisen縮合",
					startPage: 0,
					endPage: 0,
				},
			],
		},
		// ── 下巻 ──
		{
			id: 27,
			title: "有機化学における硫黄，ケイ素，リン",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "27", title: "有機化学における硫黄，ケイ素，リン", startPage: 0, endPage: 0 }],
		},
		{
			id: 28,
			title: "逆合成解析",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "28", title: "逆合成解析", startPage: 0, endPage: 0 }],
		},
		{
			id: 29,
			title: "芳香族ヘテロ環化合物I：反応",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "29", title: "芳香族ヘテロ環化合物I：反応", startPage: 0, endPage: 0 }],
		},
		{
			id: 30,
			title: "芳香族ヘテロ環化合物II：合成",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "30", title: "芳香族ヘテロ環化合物II：合成", startPage: 0, endPage: 0 }],
		},
		{
			id: 31,
			title: "飽和ヘテロ環化合物と立体電子効果",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "31", title: "飽和ヘテロ環化合物と立体電子効果", startPage: 0, endPage: 0 }],
		},
		{
			id: 32,
			title: "環状化合物の立体選択性",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "32", title: "環状化合物の立体選択性", startPage: 0, endPage: 0 }],
		},
		{
			id: 33,
			title: "ジアステレオ選択性",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "33", title: "ジアステレオ選択性", startPage: 0, endPage: 0 }],
		},
		{
			id: 34,
			title: "ペリ環状反応I：付加環化",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "34", title: "ペリ環状反応I：付加環化", startPage: 0, endPage: 0 }],
		},
		{
			id: 35,
			title: "ペリ環状反応II：シグマトロピー転位と電子環状反応",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "35", title: "ペリ環状反応II：シグマトロピー転位と電子環状反応", startPage: 0, endPage: 0 }],
		},
		{
			id: 36,
			title: "隣接基関与，転位反応，および開裂反応",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "36", title: "隣接基関与，転位反応，および開裂反応", startPage: 0, endPage: 0 }],
		},
		{
			id: 37,
			title: "ラジカル反応",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "37", title: "ラジカル反応", startPage: 0, endPage: 0 }],
		},
		{
			id: 38,
			title: "カルベンの合成と反応",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "38", title: "カルベンの合成と反応", startPage: 0, endPage: 0 }],
		},
		{
			id: 39,
			title: "反応機構の決定",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "39", title: "反応機構の決定", startPage: 0, endPage: 0 }],
		},
		{
			id: 40,
			title: "有機金属化学",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "40", title: "有機金属化学", startPage: 0, endPage: 0 }],
		},
		{
			id: 41,
			title: "不斉合成",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "41", title: "不斉合成", startPage: 0, endPage: 0 }],
		},
		{
			id: 42,
			title: "生命の有機化学",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "42", title: "生命の有機化学", startPage: 0, endPage: 0 }],
		},
		{
			id: 43,
			title: "有機化学のいま",
			startPage: 0,
			endPage: 0,
			sections: [{ id: "43", title: "有機化学のいま", startPage: 0, endPage: 0 }],
		},
	],
} satisfies Book;
